# Generated by Django 4.2.1 on 2026-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
