# Generated by Django 4.2.1 on 2026-04-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
