# Generated by Django 4.2.1 on 2026-04-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterField(
            model_name='shoes',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AddIndex(
            model_name='shoes',
            index=models.Index(fields=['-time_create'], name='shoes_shoes_time_cr_9e7c90_idx'),
        ),
    ]
