# Generated by Django 4.2.1 on 2026-05-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_category_shoes_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoes.category'),
        ),
    ]
