# Generated by Django 4.2.1 on 2026-05-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_tagpost_shoes_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('manufacturing_date', models.DateField()),
                ('country_of_origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shoes',
            name='barcode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes', to='shoes.barcode'),
        ),
    ]
