# Generated by Django 4.2.1 on 2026-06-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_barcode_shoes_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'ordering': ['-time_create'], 'verbose_name': 'Best shoes', 'verbose_name_plural': 'Best shoes'},
        ),
        migrations.AddField(
            model_name='shoes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='barcode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes', to='shoes.barcode', verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='shoes.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='shoes.tagpost', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название обуви'),
        ),
    ]
