# Generated by Django 4.2.1 on 2026-06-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_alter_category_options_alter_shoes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'ordering': ['-time_create'], 'permissions': [('discount_access', 'Can use discount access')], 'verbose_name': 'Best shoes', 'verbose_name_plural': 'Best shoes'},
        ),
    ]
