# Generated by Django 4.2.1 on 2026-09-22 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0011_shoes_author_like_comment_like_unique_shoe_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
